import { defineConfig } from "drizzle-kit"

// Migrations are generated by drizzle-kit and applied by wrangler
// (`pnpm db:migrate:local` / `pnpm db:migrate:remote`), so D1 tracks them.
export default defineConfig({
  dialect: "sqlite",
  schema: "./src/db/schema.ts",
  out: "./drizzle/migrations",
  // Only needed for `drizzle-kit studio` against the remote D1 database.
  ...(process.env.CLOUDFLARE_D1_TOKEN && {
    driver: "d1-http",
    dbCredentials: {
      accountId: process.env.CLOUDFLARE_ACCOUNT_ID ?? "",
      databaseId: process.env.CLOUDFLARE_DATABASE_ID ?? "",
      token: process.env.CLOUDFLARE_D1_TOKEN,
    },
  }),
})
