/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiV1DevicesRouteImport } from './routes/api/v1/devices'
import { Route as ApiV1FamiliesRouteImport } from './routes/api/v1/families'
import { Route as ApiV1KidsRouteImport } from './routes/api/v1/kids'
import { Route as ApiV1MeRouteImport } from './routes/api/v1/me'
import { Route as ApiV1PairRouteImport } from './routes/api/v1/pair'
import { Route as ApiV1AuthAppleRouteImport } from './routes/api/v1/auth/apple'
import { Route as ApiV1AuthDevRouteImport } from './routes/api/v1/auth/dev'
import { Route as ApiV1AuthSignOutRouteImport } from './routes/api/v1/auth/sign-out'
import { Route as ApiV1DevicesDeviceIdRouteImport } from './routes/api/v1/devices.$deviceId'
import { Route as ApiV1DevicesPushTokenRouteImport } from './routes/api/v1/devices.push-token'
import { Route as ApiV1KidsKidIdPairingCodeRouteImport } from './routes/api/v1/kids.$kidId.pairing-code'
import { Route as ApiV1KidsKidIdSessionRouteImport } from './routes/api/v1/kids.$kidId.session'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1DevicesRoute = ApiV1DevicesRouteImport.update({
  id: '/api/v1/devices',
  path: '/api/v1/devices',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1FamiliesRoute = ApiV1FamiliesRouteImport.update({
  id: '/api/v1/families',
  path: '/api/v1/families',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1KidsRoute = ApiV1KidsRouteImport.update({
  id: '/api/v1/kids',
  path: '/api/v1/kids',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1MeRoute = ApiV1MeRouteImport.update({
  id: '/api/v1/me',
  path: '/api/v1/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1PairRoute = ApiV1PairRouteImport.update({
  id: '/api/v1/pair',
  path: '/api/v1/pair',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1AuthAppleRoute = ApiV1AuthAppleRouteImport.update({
  id: '/api/v1/auth/apple',
  path: '/api/v1/auth/apple',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1AuthDevRoute = ApiV1AuthDevRouteImport.update({
  id: '/api/v1/auth/dev',
  path: '/api/v1/auth/dev',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1AuthSignOutRoute = ApiV1AuthSignOutRouteImport.update({
  id: '/api/v1/auth/sign-out',
  path: '/api/v1/auth/sign-out',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1DevicesDeviceIdRoute = ApiV1DevicesDeviceIdRouteImport.update({
  id: '/$deviceId',
  path: '/$deviceId',
  getParentRoute: () => ApiV1DevicesRoute,
} as any)
const ApiV1DevicesPushTokenRoute = ApiV1DevicesPushTokenRouteImport.update({
  id: '/push-token',
  path: '/push-token',
  getParentRoute: () => ApiV1DevicesRoute,
} as any)
const ApiV1KidsKidIdPairingCodeRoute =
  ApiV1KidsKidIdPairingCodeRouteImport.update({
    id: '/$kidId/pairing-code',
    path: '/$kidId/pairing-code',
    getParentRoute: () => ApiV1KidsRoute,
  } as any)
const ApiV1KidsKidIdSessionRoute = ApiV1KidsKidIdSessionRouteImport.update({
  id: '/$kidId/session',
  path: '/$kidId/session',
  getParentRoute: () => ApiV1KidsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/health': typeof ApiHealthRoute
  '/api/v1/devices': typeof ApiV1DevicesRouteWithChildren
  '/api/v1/families': typeof ApiV1FamiliesRoute
  '/api/v1/kids': typeof ApiV1KidsRouteWithChildren
  '/api/v1/me': typeof ApiV1MeRoute
  '/api/v1/pair': typeof ApiV1PairRoute
  '/api/v1/auth/apple': typeof ApiV1AuthAppleRoute
  '/api/v1/auth/dev': typeof ApiV1AuthDevRoute
  '/api/v1/auth/sign-out': typeof ApiV1AuthSignOutRoute
  '/api/v1/devices/$deviceId': typeof ApiV1DevicesDeviceIdRoute
  '/api/v1/devices/push-token': typeof ApiV1DevicesPushTokenRoute
  '/api/v1/kids/$kidId/pairing-code': typeof ApiV1KidsKidIdPairingCodeRoute
  '/api/v1/kids/$kidId/session': typeof ApiV1KidsKidIdSessionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/health': typeof ApiHealthRoute
  '/api/v1/devices': typeof ApiV1DevicesRouteWithChildren
  '/api/v1/families': typeof ApiV1FamiliesRoute
  '/api/v1/kids': typeof ApiV1KidsRouteWithChildren
  '/api/v1/me': typeof ApiV1MeRoute
  '/api/v1/pair': typeof ApiV1PairRoute
  '/api/v1/auth/apple': typeof ApiV1AuthAppleRoute
  '/api/v1/auth/dev': typeof ApiV1AuthDevRoute
  '/api/v1/auth/sign-out': typeof ApiV1AuthSignOutRoute
  '/api/v1/devices/$deviceId': typeof ApiV1DevicesDeviceIdRoute
  '/api/v1/devices/push-token': typeof ApiV1DevicesPushTokenRoute
  '/api/v1/kids/$kidId/pairing-code': typeof ApiV1KidsKidIdPairingCodeRoute
  '/api/v1/kids/$kidId/session': typeof ApiV1KidsKidIdSessionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/health': typeof ApiHealthRoute
  '/api/v1/devices': typeof ApiV1DevicesRouteWithChildren
  '/api/v1/families': typeof ApiV1FamiliesRoute
  '/api/v1/kids': typeof ApiV1KidsRouteWithChildren
  '/api/v1/me': typeof ApiV1MeRoute
  '/api/v1/pair': typeof ApiV1PairRoute
  '/api/v1/auth/apple': typeof ApiV1AuthAppleRoute
  '/api/v1/auth/dev': typeof ApiV1AuthDevRoute
  '/api/v1/auth/sign-out': typeof ApiV1AuthSignOutRoute
  '/api/v1/devices/$deviceId': typeof ApiV1DevicesDeviceIdRoute
  '/api/v1/devices/push-token': typeof ApiV1DevicesPushTokenRoute
  '/api/v1/kids/$kidId/pairing-code': typeof ApiV1KidsKidIdPairingCodeRoute
  '/api/v1/kids/$kidId/session': typeof ApiV1KidsKidIdSessionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/health'
    | '/api/v1/devices'
    | '/api/v1/families'
    | '/api/v1/kids'
    | '/api/v1/me'
    | '/api/v1/pair'
    | '/api/v1/auth/apple'
    | '/api/v1/auth/dev'
    | '/api/v1/auth/sign-out'
    | '/api/v1/devices/$deviceId'
    | '/api/v1/devices/push-token'
    | '/api/v1/kids/$kidId/pairing-code'
    | '/api/v1/kids/$kidId/session'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/health'
    | '/api/v1/devices'
    | '/api/v1/families'
    | '/api/v1/kids'
    | '/api/v1/me'
    | '/api/v1/pair'
    | '/api/v1/auth/apple'
    | '/api/v1/auth/dev'
    | '/api/v1/auth/sign-out'
    | '/api/v1/devices/$deviceId'
    | '/api/v1/devices/push-token'
    | '/api/v1/kids/$kidId/pairing-code'
    | '/api/v1/kids/$kidId/session'
  id:
    | '__root__'
    | '/'
    | '/api/health'
    | '/api/v1/devices'
    | '/api/v1/families'
    | '/api/v1/kids'
    | '/api/v1/me'
    | '/api/v1/pair'
    | '/api/v1/auth/apple'
    | '/api/v1/auth/dev'
    | '/api/v1/auth/sign-out'
    | '/api/v1/devices/$deviceId'
    | '/api/v1/devices/push-token'
    | '/api/v1/kids/$kidId/pairing-code'
    | '/api/v1/kids/$kidId/session'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiV1DevicesRoute: typeof ApiV1DevicesRouteWithChildren
  ApiV1FamiliesRoute: typeof ApiV1FamiliesRoute
  ApiV1KidsRoute: typeof ApiV1KidsRouteWithChildren
  ApiV1MeRoute: typeof ApiV1MeRoute
  ApiV1PairRoute: typeof ApiV1PairRoute
  ApiV1AuthAppleRoute: typeof ApiV1AuthAppleRoute
  ApiV1AuthDevRoute: typeof ApiV1AuthDevRoute
  ApiV1AuthSignOutRoute: typeof ApiV1AuthSignOutRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/devices': {
      id: '/api/v1/devices'
      path: '/api/v1/devices'
      fullPath: '/api/v1/devices'
      preLoaderRoute: typeof ApiV1DevicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/families': {
      id: '/api/v1/families'
      path: '/api/v1/families'
      fullPath: '/api/v1/families'
      preLoaderRoute: typeof ApiV1FamiliesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/kids': {
      id: '/api/v1/kids'
      path: '/api/v1/kids'
      fullPath: '/api/v1/kids'
      preLoaderRoute: typeof ApiV1KidsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/me': {
      id: '/api/v1/me'
      path: '/api/v1/me'
      fullPath: '/api/v1/me'
      preLoaderRoute: typeof ApiV1MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/pair': {
      id: '/api/v1/pair'
      path: '/api/v1/pair'
      fullPath: '/api/v1/pair'
      preLoaderRoute: typeof ApiV1PairRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/auth/apple': {
      id: '/api/v1/auth/apple'
      path: '/api/v1/auth/apple'
      fullPath: '/api/v1/auth/apple'
      preLoaderRoute: typeof ApiV1AuthAppleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/auth/dev': {
      id: '/api/v1/auth/dev'
      path: '/api/v1/auth/dev'
      fullPath: '/api/v1/auth/dev'
      preLoaderRoute: typeof ApiV1AuthDevRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/auth/sign-out': {
      id: '/api/v1/auth/sign-out'
      path: '/api/v1/auth/sign-out'
      fullPath: '/api/v1/auth/sign-out'
      preLoaderRoute: typeof ApiV1AuthSignOutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/devices/$deviceId': {
      id: '/api/v1/devices/$deviceId'
      path: '/$deviceId'
      fullPath: '/api/v1/devices/$deviceId'
      preLoaderRoute: typeof ApiV1DevicesDeviceIdRouteImport
      parentRoute: typeof ApiV1DevicesRoute
    }
    '/api/v1/devices/push-token': {
      id: '/api/v1/devices/push-token'
      path: '/push-token'
      fullPath: '/api/v1/devices/push-token'
      preLoaderRoute: typeof ApiV1DevicesPushTokenRouteImport
      parentRoute: typeof ApiV1DevicesRoute
    }
    '/api/v1/kids/$kidId/pairing-code': {
      id: '/api/v1/kids/$kidId/pairing-code'
      path: '/$kidId/pairing-code'
      fullPath: '/api/v1/kids/$kidId/pairing-code'
      preLoaderRoute: typeof ApiV1KidsKidIdPairingCodeRouteImport
      parentRoute: typeof ApiV1KidsRoute
    }
    '/api/v1/kids/$kidId/session': {
      id: '/api/v1/kids/$kidId/session'
      path: '/$kidId/session'
      fullPath: '/api/v1/kids/$kidId/session'
      preLoaderRoute: typeof ApiV1KidsKidIdSessionRouteImport
      parentRoute: typeof ApiV1KidsRoute
    }
  }
}

interface ApiV1DevicesRouteChildren {
  ApiV1DevicesDeviceIdRoute: typeof ApiV1DevicesDeviceIdRoute
  ApiV1DevicesPushTokenRoute: typeof ApiV1DevicesPushTokenRoute
}

const ApiV1DevicesRouteChildren: ApiV1DevicesRouteChildren = {
  ApiV1DevicesDeviceIdRoute: ApiV1DevicesDeviceIdRoute,
  ApiV1DevicesPushTokenRoute: ApiV1DevicesPushTokenRoute,
}

const ApiV1DevicesRouteWithChildren = ApiV1DevicesRoute._addFileChildren(
  ApiV1DevicesRouteChildren,
)

interface ApiV1KidsRouteChildren {
  ApiV1KidsKidIdPairingCodeRoute: typeof ApiV1KidsKidIdPairingCodeRoute
  ApiV1KidsKidIdSessionRoute: typeof ApiV1KidsKidIdSessionRoute
}

const ApiV1KidsRouteChildren: ApiV1KidsRouteChildren = {
  ApiV1KidsKidIdPairingCodeRoute: ApiV1KidsKidIdPairingCodeRoute,
  ApiV1KidsKidIdSessionRoute: ApiV1KidsKidIdSessionRoute,
}

const ApiV1KidsRouteWithChildren = ApiV1KidsRoute._addFileChildren(
  ApiV1KidsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiV1DevicesRoute: ApiV1DevicesRouteWithChildren,
  ApiV1FamiliesRoute: ApiV1FamiliesRoute,
  ApiV1KidsRoute: ApiV1KidsRouteWithChildren,
  ApiV1MeRoute: ApiV1MeRoute,
  ApiV1PairRoute: ApiV1PairRoute,
  ApiV1AuthAppleRoute: ApiV1AuthAppleRoute,
  ApiV1AuthDevRoute: ApiV1AuthDevRoute,
  ApiV1AuthSignOutRoute: ApiV1AuthSignOutRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
